[env:custom_tbeam_1w]
extends = esp32s3_base
board = custom_tbeam_1w
board_build.partitions = default_16MB.csv
board_check = true

build_flags = 
  ${esp32s3_base.build_flags}
  -D CUSTOM_TBEAM_1W
  -D TBEAM_V10
  -I variants/esp32s3/custom_tbeam_1w
